name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login hub
      run: docker login -u $DOCKERHUBUSER -p $DOCKERHUBTOKEN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anshen/rsync:latest
    - name: public to docker hub
      run: docker push anshen/rsync:latest

